# Generated by Django 4.1 on 2022-09-08 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagesubmit', models.ImageField(blank=True, null=True, upload_to='static/dosye_foto/')),
                ('imageresize', models.ImageField(blank=True, null=True, upload_to='static/dosye_foto/')),
            ],
        ),
    ]
