# Generated by Django 4.1 on 2022-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizeimage', '0002_alter_imageresize_imageresize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresize',
            name='Heigth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageresize',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
