# Generated by Django 4.1.1 on 2022-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizeimage', '0003_imageresize_heigth_imageresize_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageresize',
            old_name='Heigth',
            new_name='heigth',
        ),
        migrations.AlterField(
            model_name='imageresize',
            name='imageresize',
            field=models.FileField(blank=True, null=True, upload_to='dosye_foto/'),
        ),
        migrations.AlterField(
            model_name='imageresize',
            name='imagesubmit',
            field=models.FileField(blank=True, null=True, upload_to='dosye_foto/'),
        ),
    ]
